name: Badge Generator
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: python .github/scripts/generate_badges.py
      - run: |
          git config --global user.name "BadgeBot"
          git config --global user.email "bot@github.com"
          git add badges/*.svg
          git commit -m "Update badges" || exit 0
          git push
